version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: money-transfer-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: money_transfer
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: money-transfer-redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: money-transfer-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
  minio-data:
